#######################################################################################################################
# Upsun demo project configuration
#######################################################################################################################
# Application configuration.
applications:    
    # App 1: Frontend (JS)
    frontend:

        source:
            root: "frontend"

        type: "nodejs:18"

        build:
            flavor: none
        variables:
            env:
                N_PREFIX: /app/.global
        hooks:
            build: |
                set -e
                npm install
                npm run build
            deploy: >
                set -eux

                echo "Add some deploy commands here if you like."

        web:
            locations:
                /:
                    root: build
                    index:
                        - index.html
                    expires: 2m
                    scripts: false
                    allow: true
                    rules:
                        static\/*:
                            expires: 365d
                        dynamic\/*:
                            expires: -1

        mounts:
            /build/dynamic:
                source: local
                source_path: build/dynamic
    # App 2: Backend (Python)
    backend:

        source:
            root: "backend"

        type: "python:3.11"

        build:
            flavor: none
        hooks:
            build: |
                set -eux
                pip install --upgrade pip
                pip install -r requirements.txt
                
        web:
            commands:
                start: "gunicorn main:app"
            upstream:
                socket_family: tcp
            locations:
                /:
                    passthru: true

#         relationships:
#             redis-session: "redis_persistent:redis-persistent"

# Managed services configuration.
# services:
#     redis_persistent:
#         type: "redis-persistent:7.0"
        
# Routes configuration.
routes:
    "https://{default}/":
        id: frontend
        type: upstream
        upstream: "frontend:http"

    "https://www.{default}":
        id: www-redirect
        type: redirect
        to: "https://{default}/"

    "https://{default}/api/":
        id: backend
        type: upstream
        upstream: "backend:http"